### ISSUE TITLE
OCR 솔루션 조사. 솔루션별로 비교해 적합한 솔루션 선정하기.

### ISSUE THREAD

**Issue by simba3447** [simba3447/honey-jam-hack-jam#1]
퀴즈 본문과 보기의 텍스트를 추출할 OCR 솔루션을 조사하고 특징에 따라 프로젝트에 적합한 솔루션 선정하기

**Comment by simba3447** [comment]
@baehaeli 3월 8일까지 진행해주세욥!!!

**Comment by baehaeli** [comment]
# **OCR**

## 광학 문자 인식

보통 컴퓨터가 이진법(0/1) 데이터를 폰트를 통해 인간이 인식할 수 있는 형태로 글자를 보여 준다면, OCR 은 그 반대로 인간이 종이 위에 써 놓은 글씨를 인지하여 텍스트 데이터로 치환한다. 보통은 스캐너로 읽어들인 이미지 파일을 분석하여 텍스트나 워드 파일로 결과물을 내놓는다.


## 문자인식 기능 웹사이트

http://ocr.retia.co.kr
   AABBY와 동일한 엔진을 제공하며 간단한 전환 기능을 제공함(한글, 영어 인식 가능)

http://www.finereaderonline.com/en-us
    ocr.retia.co.kr 과 동일한 외국 사이트(한글, 영어, 일본어, 중국어 인식 가능)


## PC용 문자인식 프로그램
-ABBYY FineReader
-아르미(단종)
-Readiris Corp
-Acrobat Pro XI


1)ABBYY

ABBYY 파인리더(ABBYY FineReader)는 문서인식(광학식 문자 인식) 프로그램이다.
ABBYY 파인리더는 이미지 또는 PDF파일을 편집 가능한 문서로 변환해 주는 지능형 OCR(문자인식) 소프트웨어
이다.

주요기능은 다음과 같다.

각종 이미지파일(pdf, jpg, png, tiff 등)을 편집가능한 Word, Excel 파일로 변환
각종 이미지파일을 검색가능한 pdf 파일로 생성 (텍스트 레이어 포함)
PDF 에디터 제공 1. (스캔PDF, 디지털PDF 모두 텍스트 편집,수정 가능)
PDF 에디어 제공 2.(메모삽입, PDF생성, 합치기, 암호보호, 공유 등 PDF편집에 필요한 필수 기능 모두 제공)
고급 OCR편집기능 제공 1. (인식성능 및 레이아웃 복원율을 높일 수 있는 편집도구 제공, 복잡한 표의 구조를 그대로 복원 가능)
고급 OCR편집기능 제공 2. (인식 신뢰도가 낮은 글자만 하이라이트 처리 및 직관적 검증 도구)
스캐너에서 생성된 문서 뿐 아니라 모바일 카메라로 촬영한 사진도 인식 가능
EBOOK파일 생성 가능
OCR 배치작업 제공 (폴더 지정하여, 폴더 속 파일을 일괄적으로 순차 변환 가능. 기업용 에디션부터 사용 가능)
문서비교 기능 제공 (서로 다른 포맷의 두 개 의 문서의 텍스트 변경사항을 감지하여 알려줌. 기업용 에디션부터 사용 가능)


2)Adobe의 Acrobat Pro/DC
1년 약정 걸면 현재 Acrobat DC 이 프로그램 하나만 월 1만 8천원으로 구독 가능


3)IRIS READIRS
개인 사용자용 $99


모두 텍스트 파일, pdf 파일로 변경 가능

오픈소스 ocr은 tesseract 밖에 없음.


참고문헌
http://gongboobub.tistory.com/8

http://egloos.zum.com/mcchae/v/11272572

http://freestrokes.tistory.com/entry/Ubuntu-Tess4J-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0-JNA-wrapper-for-Tesseract


http://sehyo88.tistory.com/entry/tesseractocr-%EC%97%90%EC%84%9C-%ED%95%9C%EA%B8%80-%EB%AC%B8%EC%9E%90%EC%9D%B8%EC%8B%9D%EC%9D%98-%EB%AC%B8%EC%A0%9C%EC%A0%90
