### ISSUE TITLE
문제 데이터 수집. 유형별 분류, 접근 방식 생각해보기

### ISSUE THREAD

**Issue by simba3447** [simba3447/honey-jam-hack-jam#3]
기존에 출제되었던 문제들을 수집해 분류하고 어떤 식으로 검색하고 정답을 도출해낼지 생각해본다.

**Comment by simba3447** [comment]
@NamHyunSil 마감 일자 어떻게 만드는지 모르겠네. 3월 8일까지 조사해주세용

**Comment by NamHyunSil** [comment]
# 문제유형과 그에 따른 방법
1. **한가지 주제에 해당하는 것**(한가지 대상에 대한 설명을 한뒤 그 대상을 맞추는 것) - 문장 또는 문장 속의 키워드를 검색하고 페이지 내에 3가지 답 중 find 빈도가 제일 많이 나온 답을 추천해주도록 함
2. **하나의 주제해 해당하지 않는 것** - 1번과 같은 방법으로 검색 후에 답 키워드 find 빈도가 제일 낮은 것
3. **국어(맞춤법/표현법)** - 맞춤법/표현법 검사하는 사이트를 이용하여 true false 검사
4. **계산(숫자/수 와 '합친','뺀'과 같은 단어/사칙연산 기호 포함 인 경우)** - 숫자와 사칙연산만 있으면 그대로 계산 / 문장일 땐 키워드를 검색하고 숫자로 나타내어 사칙연산 함
5. **짝** - 짝으로 이루어 진 것 끼리 한꺼번에 검색 후 검색 결과가 가장 적은 것 or 가장 높은 것
6. **사전 검색**- 사전에서 검색 후 알맞게 결과 추출(더 생각해볼 것)
7. **답이 문장** - 답에서 키워드를 추출하여  find 빈도수의 합이 제일 높은 것
8. **특정 문제**(가사 속 특정 단어 개수, 맹자의 집터 이동경로, 설립시기 비교) - 더 생각해볼 것

-문제 140개를 추출하여 분류한 것임.
-1, 2번 문제유형이 대부분을 차지했고 그 중 1번 유형이 제일 많이 쓰였다. 그러므로 우선 1, 2번이 잘 작동되도록 구현하는 것이 첫번째 목표라고 생각함.
